{
    # displayName: "Hiconic Monolitic Release",
    repositoryPrototype: !com.braintribe.devrock.model.repository.IndexedMavenHttpRepository {
        name: "hiconic-monolithic-release",
        url: "https://maven.pkg.github.com/hiconic-os/maven-repo-dev",
        user: "ignored",
        password: "${env.GITHUB_READ_PACKAGES_TOKEN}"
    },
    includes: [
        "*"
    ],
    excludes: [
        
    ],
}
